SearchBar list component, redux fixed, refresh searchBar Component
camilovegag/shrine pull request #2
Opened 2021-11-25 16:51 UTC by mariasaavega

separate search bar and list component, update the reducer filter and when returning to the search bar the previous search no longer appears

2021-11-25 16:52 UTC, mariasaavega commented
separate search bar and list component, update the reducer filter and when returning to the search bar the previous search no longer appears

2021-11-25 19:00 UTC, camilovegag requested changes
I left some comments!

2021-11-25 19:00 UTC, camilovegag commented on components/SearchBar/index.jsx
> +  const inputValue = React.useRef(null);
Why not importing useRef from react, such as { useEffect }

2021-11-25 19:00 UTC, camilovegag commented on components/SearchBar/index.jsx
>          console.log("No results")
Can you show a No results found Text underneath the search bar instead?

2021-11-25 19:00 UTC, camilovegag commented on components/SearchBar/index.jsx
> +  const getInitialData = async () => {}
What is this function doing?

2021-11-25 19:00 UTC, camilovegag commented on components/SearchList/index.jsx
> +    data={props.list}
You can destructure `list` from `SearchList({ list })`, avoiding the use of props keyword

2021-11-25 19:00 UTC, camilovegag commented on components/SearchList/index.jsx
> +            props.navigate("UserResult",{
Same here, `props.navigate` can be replaced with `navigation.navigate`. Your function may look like this: 
`SearchList({ list, navigation })`

2021-11-25 19:00 UTC, camilovegag commented on components/SearchBar/index.jsx
> +        <SearchList list = {filteredList["text"]} {...navigation} />
The `navigation` prop is passed down to components by default, so I think you can remove `{...navigation}` and SearchList will be able to access it.

2021-11-25 19:00 UTC, camilovegag commented on components/SearchBar/index.jsx
>    return <AppWrapper {...navigation} />;
Maybe the `<AppWrapper />` isn't necessary if you destructure `{ navigation }` on the actual component?

2021-11-26 17:32 UTC, mariasaavega commented on components/SearchBar/index.jsx
> +        <SearchList list = {filteredList["text"]} {...navigation} />
When removed, it stops working because it is not passed by default

2021-11-26 17:38 UTC, closed without merging